# Generated by Django 5.2.7 on 2025-11-17 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('dojo_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.dojoclass')),
            ],
        ),
    ]
